//@ sourceMappingURL=app.map
// Generated by CoffeeScript 1.6.1
(function() {
  var app, db, dbUri, dbUrl, express, flash, fs, http, io, models_path, mongoOptions, mongoStore, mongoose, passport, path, port, server, viewHelpers;

  require('coffee-script');

  fs = require('fs');

  express = require('express');

  http = require('http');

  path = require('path');

  io = require('socket.io');

  mongoose = require('mongoose');

  mongoStore = require('connect-mongo')(express);

  flash = require('connect-flash');

  passport = require('passport');

  viewHelpers = require('./config/middlewares/view');

  app = express();

  dbUri = process.env.MONGOLAB_URI || process.env.MONGOHQ_URL || 'mongodb://localhost/danceAndNews';

  port = process.env.PORT || 3000;

  require('./config/config')(app);

  dbUrl = app.get('dbUrl');

  mongoOptions = {
    db: {
      safe: true
    }
  };

  db = mongoose.connect(dbUrl, mongoOptions, function(err, res) {
    if (err) {
      console.log("ERROR connecting to: " + dbUrl + ". " + err);
    } else {
      console.log('Succeeded connected to: ' + dbUrl);
    }
  });

  models_path = __dirname + '/app/models';

  fs.readdirSync(models_path).forEach(function(file) {
    if (file.slice(-2) === "js") {
      return require(models_path + '/' + file);
    }
  });

  require('./config/passport')(app);

  app.configure('development', function() {
    app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: false
    }));
  });

  app.configure('production', function() {
    app.use(express.errorHandler());
  });

  app.configure(function() {
    app.use(viewHelpers(app));
    app.use(express.favicon());
    app.use(express.logger('dev'));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(express.cookieParser("secret-dance-and-news"));
    app.use(express.session({
      secret: 'secret-dance-and-news',
      store: new mongoStore({
        url: app.get('dbUrl'),
        collection: 'sessions'
      })
    }));
    app.use(flash());
    app.use(passport.initialize());
    app.use(passport.session());
    app.use(app.router);
    app.use(express["static"](path.join(__dirname, 'public')));
  });

  require('./config/routes')(app);

  server = http.createServer(app);

  io = io.listen(server);

  server.listen(app.get("port"), function() {
    return console.log("Express server listening on port " + app.get("port"));
  });

  io.configure(function() {
    io.set("transports", ["xhr-polling"]);
    io.set("polling duration", 10);
    io.set('log level', 1);
  });

  io.sockets.on("connection", function(socket) {
    socket.emit("news", {
      hello: "hello"
    });
    socket.on("my other event", function(data) {
      console.log(data);
    });
  });

}).call(this);
