// Generated by CoffeeScript 1.4.0
(function() {
  var app, db, dbUri, express, http, io, mongoOptions, mongoStore, mongoose, passport, path, port, routes, server, user;

  require('coffee-script');

  express = require('express');

  routes = require('./config/routes/');

  user = require('./config/routes/user');

  http = require('http');

  path = require('path');

  io = require('socket.io');

  mongoose = require('mongoose');

  mongoStore = require('connect-mongodb');

  passport = require('passport');

  app = express();

  dbUri = process.env.MONGOLAB_URI || process.env.MONGOHQ_URL || 'mongodb://localhost/danceAndNews';

  port = process.env.PORT || 3000;

  mongoOptions = {
    db: {
      safe: true
    }
  };

  db = mongoose.connect(dbUri, mongoOptions, function(err, res) {
    if (err) {
      console.log("ERROR connecting to: " + dbUri + ". " + err);
    } else {
      console.log("Succeeded connected to: " + dbUri);
    }
  });

  require('./config/config')(app);

  app.configure('development', function() {
    app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: false
    }));
  });

  app.configure('production', function() {
    app.use(express.errorHandler());
  });

  app.configure(function() {
    app.use(express.favicon());
    app.use(express.logger('dev'));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(express.cookieParser("secretdancenews"));
    app.use(express.session({
      store: mongoStore(app.set('db-uri'), {
        secret: 'keyboard cat'
      })
    }));
    app.use(passport.initialize());
    app.use(passport.session());
    app.use(app.router);
    app.use(express["static"](path.join(__dirname, 'public')));
  });

  app.get('/', routes.index);

  app.get('/users', user.list);

  server = http.createServer(app);

  io = io.listen(server);

  server.listen(app.get("port"), function() {
    return console.log("Express server listening on port " + app.get("port"));
  });

  io.configure(function() {
    io.set("transports", ["xhr-polling"]);
    io.set("polling duration", 10);
    io.set('log level', 1);
  });

  io.sockets.on("connection", function(socket) {
    socket.emit("news", {
      hello: "hello"
    });
    socket.on("my other event", function(data) {
      console.log(data);
    });
  });

}).call(this);
