// Generated by CoffeeScript 1.4.0

/*
Pagination helper

@param {Number} pages
@param {Number} page
@return {String}
@api private
*/


(function() {
  var createPagination, formatDate, stripScript;

  createPagination = function(req) {
    return createPagination = function(pages, page) {
      var clas, p, params, qs, str, url;
      url = require("url");
      qs = require("querystring");
      params = qs.parse(url.parse(req.url).query);
      str = "";
      params.page = 0;
      clas = (page === 0 ? "active" : "no");
      str += "<li class=\"" + clas + "\"><a href=\"?" + qs.stringify(params) + "\">First</a></li>";
      p = 1;
      while (p < pages) {
        params.page = p;
        clas = (page === p ? "active" : "no");
        str += "<li class=\"" + clas + "\"><a href=\"?" + qs.stringify(params) + "\">" + p + "</a></li>";
        p++;
      }
      params.page = --p;
      clas = (page === params.page ? "active" : "no");
      str += "<li class=\"" + clas + "\"><a href=\"?" + qs.stringify(params) + "\">Last</a></li>";
      return str;
    };
  };

  /*
  Format date helper
  
  @param {Date} date
  @return {String}
  @api private
  */


  formatDate = function(date) {
    var monthNames;
    monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sep", "Oct", "Nov", "Dec"];
    return monthNames[date.getMonth()] + " " + date.getDate() + ", " + date.getFullYear();
  };

  /*
  Strip script tags
  
  @param {String} str
  @return {String}
  @api private
  */


  stripScript = function(str) {
    return str.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/g, "");
  };

  module.exports = function(app) {
    return function(req, res, next) {
      res.locals.appName = app.get('app').name;
      res.locals.title = app.get('title');
      res.locals.req = req;
      res.locals.isActive = function(link) {
        if (req.url === link) {
          return "active";
        } else {
          return "";
        }
      };
      res.locals.formatDate = formatDate;
      res.locals.stripScript = stripScript;
      res.locals.createPagination = createPagination(req);
      next();
    };
  };

}).call(this);
