//@ sourceMappingURL=routes.map
// Generated by CoffeeScript 1.6.1
(function() {
  var User, mongoose, passport;

  mongoose = require("mongoose");

  passport = require("passport");

  User = mongoose.model("User");

  module.exports = function(app) {
    var users;
    users = require('../app/controllers/users');
    app.get('/login', users.login);
    app.get('/signup', users.signup);
    app.get('/logout', users.logout);
    app.post('/users', users.create);
    app.get('/auth/vkontakte', passport.authenticate('vkontakte-email', {
      scope: ['audio', 'video', 'offline'],
      failureRedirect: '/login',
      failureFlash: true
    }), users.signin);
    app.get('/auth/vkontakte/callback', passport.authenticate('vkontakte-email', {
      failureRedirect: '/login',
      failureFlash: true
    }));
    app.get('/auth/vkontakte/addemail', users.authGetEmailCallback);
    app.post('/auth/vkontakte/addemail', passport.authenticate('vkontakte-email', {
      failureRedirect: '/login',
      failureFlash: true
    }), users.authCallback);
    app.get('/auth/facebook', passport.authenticate('facebook', {
      scope: ['email', 'user_about_me'],
      failureRedirect: '/login',
      failureFlash: true
    }), users.signin);
    app.get('/auth/facebook/callback', passport.authenticate('facebook', {
      failureRedirect: '/login',
      failureFlash: true
    }), users.authCallback);
    app.get('/auth/google', passport.authenticate('google', {
      scope: ['https://www.googleapis.com/auth/userinfo.email', 'https://www.googleapis.com/auth/userinfo.profile', 'https://gdata.youtube.com', 'https://www.googleapis.com/auth/plus.me'],
      failureRedirect: '/login',
      failureFlash: true
    }), users.signin);
    app.get('/auth/google/callback', passport.authenticate('google', {
      failureRedirect: '/login',
      failureFlash: true
    }), users.authCallback);
    app.get('/', function(req, res) {
      res.render("index", {
        title: "danseAndNews"
      });
    });
  };

}).call(this);
