// Generated by CoffeeScript 1.6.1
(function() {

  exports.addEvent = function(req, res) {
    debugger;    req.app.io.route('add-event', function(req) {
      console.log(req.data);
    });
    res.render("events/addEvent", {
      title: "add Event",
      scripts: ['/js/events.client.js']
    });
  };

}).call(this);
