//@ sourceMappingURL=index.map
// Generated by CoffeeScript 1.6.1
(function() {

  exports.index = function(req, res) {
    res.render("index", {
      title: "danseAndNews"
    });
  };

}).call(this);
