//@ sourceMappingURL=users.map
// Generated by CoffeeScript 1.6.1
(function() {
  var User, mongoose, passport;

  mongoose = require("mongoose");

  User = mongoose.model("User");

  passport = require("passport");

  exports.signin = function(req, res) {
    res.redirect("/");
  };

  exports.login = function(req, res) {
    res.render("users/login", {
      title: "Login",
      message: req.flash("error")
    });
  };

  exports.authCallback = function(req, res, next) {
    res.redirect("/");
  };

  exports.authGetEmailCallback = function(req, res) {
    return res.render("users/getEmail", {
      title: "getEmail",
      message: req.flash("error")
    });
  };

  exports.create = function(req, res, next) {
    passport.authenticate("vkontakte-email", function(err, user, info) {
      if (err) {
        return next(err);
      }
      if (!user) {
        return res.redirect("/login");
      }
      res.redirect('/');
    })(req, res, next);
  };

  exports.test = function(req, res, next) {
    console.log(req);
    next();
  };

  exports.signup = function(req, res) {
    res.render("users/signup", {
      title: "Sign up",
      user: new User()
    });
  };

  exports.logout = function(req, res) {
    req.logout();
    return res.redirect("/login");
  };

  exports.session = function(req, res) {
    res.redirect("/");
  };

}).call(this);
