// Generated by CoffeeScript 1.6.1
(function() {
  var Schema, eventSchema, mongoose, validate;

  validate = require('mongoose-validate');

  mongoose = require("mongoose");

  Schema = mongoose.Schema;

  eventSchema = new Schema({
    dateBegin: Date,
    dateEnd: Date,
    inStackNews: [],
    inTimeLineNews: [],
    video: {}
  });

  mongoose.model("Event", eventSchema);

}).call(this);
