//@ sourceMappingURL=news.map
// Generated by CoffeeScript 1.6.1
(function() {
  var mongoose, validate;

  validate = require('mongoose-validate');

  mongoose = require("mongoose");

}).call(this);
